### ISSUE TITLE
Error for multi-hits and no hits using get_termite_dataframe()

### ISSUE THREAD

**Issue by janelomax** [SciBiteLabs/termite_toolkit#10]
Attach sample script with some examples. Hopefully should be self-explanatory. You'll need MDRAELLY loaded.

Also same problem for get_entity_hits_from_json().

[joem_test.py.zip](https://github.com/SciBiteLabs/termite_toolkit/files/3290360/joem_test.py.zip)

**Comment by rachaellturner** [comment]
I did some testing with this (Termite version: 6.3.17).
When I ran the script I got the response: "Can't process:  abdominal cramp"

In the Termite UI: 'abdominal' hits are ambiguous, the toolkit filters these out by default (and the script specifies for ambiguous hits to be rejected)
![image](https://user-images.githubusercontent.com/33983816/59614722-34f21100-9119-11e9-977a-6eb9b08dbb1e.png)

To get the hits you're expecting from "abdominal cramp", you need to specify in the TERMite options "rejectAmbig": "False" and specify "reject_ambig=False" as an arguement in get_termite_dataframe (same for get_entity_hits_from_json)

@janelomax, do you get the result you're expecting if you make these changes?

**Comment by janelomax** [comment]
Oh sorry take the try/except block out of the script and try running again, didn't mean to leave those in! I was getting errors because I think the dataframe is the wrong size for the data coming in if there are >1 hits, or if there are no hits.

**Comment by janelomax** [comment]
It was a key error or something

**Comment by janelomax** [comment]
(with the try/except removed)

**Comment by JMMull** [comment]
@janelomax please pull the latest version of the toolkit from PyPi (0.2.3) @rachaellturner is quite right, the reason you were getting no hits for "abdominal cramp" was due to the non-ambig hits being filtered by default, however there was indeed a bug when the dataframe contained no rows, this has now been rectified and can be shown to work in the attached script, cheers, Joe
[joem_test.py 2.zip](https://github.com/SciBiteLabs/termite_toolkit/files/3297853/joem_test.py.2.zip)
